version: '3'

services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
  database:
    image: mysql:5.7.43
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secretpassword123
      - MYSQL_ROOT_HOST=%